PeopleManager.Ui.Mvc/Controllers/OrganizationsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Dto.Requests;
using PeopleManager.Dto.Results;
using PeopleManager.Sdk;

namespace PeopleManager.Ui.Mvc.Controllers
{
    [Authorize]
    public class OrganizationsController : Controller
    {
        private readonly OrganizationSdk _organizationSdk;

        public OrganizationsController(OrganizationSdk organizationSdk)
        {
            _organizationSdk = organizationSdk;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var organizations = await _organizationSdk.Find();
            return View(organizations);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(OrganizationRequest request)
        {
            if (!ModelState.IsValid)
            {
                var organization = new OrganizationResult
                {
                    Name = request.Name,
                    Description = request.Description
                };
                return View(organization);
            }

            await _organizationSdk.Create(request);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute] int id)
        {
            var result = await _organizationSdk.Get(id);

            if (!result.IsSuccess || result.Data is null)
            {
                return RedirectToAction("Index");
            }

            return View(result.Data);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int id, [FromForm] OrganizationRequest request)
        {
            if (!ModelState.IsValid)
            {
                var result = await _organizationSdk.Get(id);
                if (!result.IsSuccess || result.Data is null)
                {
                    return RedirectToAction("Index");
                }
                var organization = result.Data;
                organization.Name = request.Name;
                organization.Description = request.Description;

                return View(organization);
            }

            await _organizationSdk.Update(id, request);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            var result = await _organizationSdk.Get(id);
            if (!result.IsSuccess || result.Data is null)
            {
                return RedirectToAction("Index");
            }
            return View(result.Data);
        }

        [HttpPost("/[controller]/Delete/{id:int?}"), ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _organizationSdk.Delete(id);

            return RedirectToAction("Index");
        }
    }
}

PeopleManager.Ui.Mvc/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PeopleManager.Dto.Requests;
using PeopleManager.Dto.Results;
using PeopleManager.Sdk;

namespace PeopleManager.Ui.Mvc.Controllers
{
    [Authorize]
    public class PeopleController : Controller
    {
        private readonly PersonSdk _personSdk;
        private readonly OrganizationSdk _organizationSdk;

        public PeopleController(
            PersonSdk personSdk,
            OrganizationSdk organizationSdk)
        {
            _personSdk = personSdk;
            _organizationSdk = organizationSdk;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var people = await _personSdk.Find();

            return View(people);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            return await CreateEditView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PersonRequest request)
        {
            if (!ModelState.IsValid)
            {
                var person = new PersonResult
                {
                    FirstName = request.FirstName,
                    LastName = request.LastName,
                    Email = request.Email
                };

                return await CreateEditView(person);
            }

            await _personSdk.Create(request);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Edit([FromRoute]int id)
        {
            var result = await _personSdk.Get(id);

            if (!result.IsSuccess || result.Data is null)
            {
                return RedirectToAction("Index");
            }

            return await CreateEditView(result.Data);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute]int id, [FromForm]PersonRequest request)
        {
            if (!ModelState.IsValid)
            {
                var result = await _personSdk.Get(id);
                if (!result.IsSuccess || result.Data is null)
                {
                    return RedirectToAction("Index");
                }

                var person = result.Data;
                person.FirstName = request.FirstName;
                person.LastName = request.LastName;
                person.Email = request.Email;

                return await CreateEditView(person);
            }

            await _personSdk.Update(id, request);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Delete([FromRoute] int id)
        {
            var person = await _personSdk.Get(id);

            return View(person.Data);
        }

        [HttpPost("/[controller]/Delete/{id:int?}"), ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _personSdk.Delete(id);

            return RedirectToAction("Index");
        }
        
        private async Task<IActionResult> CreateEditView(PersonResult? person = null)
        {
            var organizations = await _organizationSdk.Find();
            ViewBag.Organizations = organizations;
            return View(person);
        }
    }
}

PeopleManager.Ui.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PeopleManager.Ui.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PeopleManager.Ui.Mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PeopleManager.Ui.Mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
	                <ul class="navbar-nav flex-grow-1">
		                @if (User.Identity is not null && User.Identity.IsAuthenticated)
		                {
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About me!</a>
			                </li>

			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="People" asp-action="Index">People</a>
			                </li>
			                <li class="nav-item">
				                <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Index">Organizations</a>
			                </li>
		                }
	                </ul>
	                <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PeopleManager.Ui.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    @await RenderSectionAsync("Modals", required: false)

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>